### ISSUE TITLE
netcat version shipped does not support -U (unix sockets) option - prevents libvirtd from being remotely managed

### ISSUE THREAD

**Issue by aenertia** [clearlinux/common#10]
virt-manager relies on the target remote hypervisor to bind to a unix socket via a netcat pipe. 

The netcat binary shipped in clearlinux does not support this option. Please rebuild/ship with a version supporting this.

**Comment by phmccarty** [comment]
@aenertia Can you open an issue at https://github.com/clearlinux/distribution instead?

**Comment by phmccarty** [comment]
I'll move it

**Comment by phmccarty** [comment]
Moved to https://github.com/clearlinux/distribution/issues/153
