### ISSUE TITLE
"ruamel.yaml" in file 'packages' should match the repo name.

### ISSUE THREAD

**Issue by youzhongyang** [clearlinux/common#13]
"ruamel.yaml" in file 'packages' does not match repo name (https://github.com/clearlinux-pkgs/ruamel-yaml), thus causing 'make clone' failure.

**Comment by phmccarty** [comment]
Thanks, this is a bug with the repo publishing to Github. I will investigate.

**Comment by phmccarty** [comment]
The publishing issue has been fixed and the `ruamel.yaml` repo is now available:

https://github.com/clearlinux-pkgs/ruamel.yaml

Since `ruamel.yaml` was recently renamed from `ruamel-yaml`, the packages file is correct. Thanks again for the report!
