### ISSUE TITLE
mv debuginfo makes build fail if no debuginfo RPMs were generated

### ISSUE THREAD

**Issue by bwarden** [clearlinux/common#6]
```
INFO: Results and/or logs in: results/
Finish: run
mkdir -p results/logs results/debuginfo
mv results/*.log results/logs
mv results/*-debuginfo*.rpm results/debuginfo/
mv: cannot stat 'results/*-debuginfo*.rpm': No such file or directory
make: *** [../common/Makefile.common:96: build] Error 1
```

Not all components provide a debuginfo package. Perhaps using `-f` with `mv` would be more appropriate so `make` doesn't fail here.

**Comment by phmccarty** [comment]
Oh right, this happens for packages with binary stripping disabled?

**Comment by sysarcher** [comment]
@phmccarty I'm facing the same issue while building `linux-pk414`.

**Comment by phmccarty** [comment]
@shrmrf The `mv` command is still attempted, but the exit status is ignored now. You should see these lines near the end of the output:

```
mkdir -p results/logs results/debuginfo
mv results/*.log results/logs
mv results/*-debuginfo*.rpm results/debuginfo/
mv: cannot stat 'results/*-debuginfo*.rpm': No such file or directory
make: [../common/Makefile.common:96: build] Error 1 (ignored)
```

And the exit status of make should be `0`.

**Comment by sysarcher** [comment]
@phmccarty yup, you're right. i noticed that the output `rpm` file was present as well. Sorry for not getting back earlier.

**Comment by fenrus75** [comment]
we should actually undo the moving of useful stuff out of results/
if nothing else only the rpms should move (or hardlink) to somewhere else
if all we want is a dir with just rpms
