### ISSUE TITLE
os-clr-on-clr   Bundle too large by 10811M

### ISSUE THREAD

**Issue by ksaltik** [clearlinux/common#8]
os-clr-on-clr   Bundle too large by 10811M

I use Debian and other Linux and FreeBSD but this is too much 10811M of download. Don't follow the steps of Yarn packaging for Npm their. Your bundles or not meaningful what if I only need just one package from your bundle. I need very simple things nginx redis mariadb php nothing else but when I try to install how many more package I installed to the system. 

I know clear linux is not for ordinary users why do you make them public

**Comment by fenrus75** [comment]
so os-clr-on-clr is close to an "everything" install which some people want
if they do not care about size but want just one thing to install

there should be bundles that are much smaller that get you what you need...

nginx is it's own mini bundle
php-basic is basics for php
database-basic gets you mariadb
redis-native gets you just redis

**Comment by phmccarty** [comment]
This issue is unrelated to the common repo, so I am closing it.

Please report any concerns about bundle size to https://github.com/clearlinux/distribution.
